server:
  port: 8081
  #tomcat:
   # threads:
    #  max: 200
     # max-queue-capacity: 100
      #min-spare: 10
spring:
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    hospital:
      jdbcUrl: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
      driver-class-name: oracle.jdbc.OracleDriver
      username: EMPLOYEE
      password: dudkrish1A@
      hikari:
        pool-name: HikariPrimary
        maximum-pool-size: 10
        properties:
          hibernate:
            dialect: org.hibernate.dialect.OracleDialect
    order:
      jdbcUrl: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
      driver-class-name: oracle.jdbc.OracleDriver
      username: EMPLOYEE
      password: dudkrish1A@
      hikari:
        pool-name: HikariPrimary
        maximum-pool-size: 10
        properties:
          hibernate:
            dialect: org.hibernate.dialect.OracleDialect
    emp:
      jdbcUrl: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
      driver-class-name: oracle.jdbc.OracleDriver
      username: EMPLOYEE
      password: dudkrish1A@
      hikari:
        pool-name: HikariPrimary
        maximum-pool-size: 10
        properties:
          hibernate:
            dialect: org.hibernate.dialect.OracleDialect
    #url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    #driver-class-name: oracle.jdbc.OracleDriver
    #username: EMPLOYEE
    #password: dudkrish1A@
    jpa:
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.Oracle12cDialect

  sql:
    init:
      continue-on-error: true
  cache:
    type: redis
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE