apiVersion: v1
kind: ConfigMap
metadata:
  name: data-service-configs
  namespace: kubernetes-dashboard
data:
  FAKE_REST_SERVICE: "http://fake-rest-service/fake"
  ORACLE_HOST: "host.docker.internal"